### ISSUE TITLE
Personalize text and colors

### ISSUE THREAD

**Issue by sudfr** [JoomBall/JBCookies#27]
Hi,
Thanks for your extension,
How and where is it possible on Joomla 4 with Joomball Cookie to personalize the text (in French langage for exemple).
I made modification on the idfferents colors but with no effect...
Thanks

**Comment by JoomBall** [comment]
Hi @sudfr,

I have updated module mod_jbcookies 4.0.1 fixing 2 errors [https://github.com/JoomBall/JBCookies/releases/tag/4.0.1](https://github.com/JoomBall/JBCookies/releases/tag/4.0.1)

Update module so that the option to customize colors works correctly.


![Update](https://user-images.githubusercontent.com/16047586/148114633-140e5358-63b7-4e35-bc6c-8cdcf88eeb0b.png)


Custom template

![Custom](https://user-images.githubusercontent.com/16047586/148114683-ef4d6cfe-528c-4f04-92ae-8006ffe4dfbc.png)


Add custom text

![langs](https://user-images.githubusercontent.com/16047586/148114696-22980ca0-2e72-4ecb-be04-bd29c8c6e573.png)
